kind: Secret
apiVersion: v1
metadata:
  namespace: vf-test
  name: vf-app-test-frontend
  annotations:
    avp.kubernetes.io/path: "vf-dev/data/vf-app-dev-frontend"
type: Opaque
stringData:
  CLIENT_ID: <CLIENT_ID>
  CLIENT_SECRET: <CLIENT_SECRET>
  GITHUB_APP_ID: <GITHUB_APP_ID>
  GITHUB_APP_SECRET: <GITHUB_APP_SECRET>
  REDIS_PASSWORD: <REDIS_PASSWORD>
  SESSION_SECRET: <SESSION_SECRET>
