name: Copy commits

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Version of release'     
        required: true
      DRY_RUN:
        description: 'Preview changes'
        default: true
env:
  GIT_HASH: ${{ vars.LAST_GITHUB_SHA }}

jobs:
  release_code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo
        uses: actions/checkout@v2
        with:
          path: private_repo
          ref: main
      - name: Clone public repo
        uses: actions/checkout@v2
        with:
          path: public_repo2
          token: ${{ secrets.GIT_PASS }}
          repository: ${{ vars.PUBLIC_REPO }}
          ref: main
#       - name: Clean public repo
#         run: |
#           set -e
#           mkdir -p public_repo
#           mv public_repo2/.git public_repo/
#           rm -rf public_repo2
#       - name: Copy release
#         run: |
#           set -e
#           rsync -crlvE ./private_repo/ ./public_repo/ \
#           --exclude .git --exclude .travis.yml --exclude .github \
#           --exclude sonar-project.properties
      - name: Commits to public repo
        run: |
          set -e
          cd public_repo2
          git config user.email "ishautsou@ibagroup.eu"
          git config user.name "Ihar Shautsou"
          git status
          git remote add private https://github.com/${{ github.repository }}.git
          git remote update
          echo https://github.com/${{ github.repository }}.git
          echo ${{ env.GIT_HASH }}
          git merge --allow-unrelated-histories ${{ env.GIT_HASH }}
          if [[ "${{ github.event.inputs.DRY_RUN }}" != "true" ]]; then
            git push origin main
          fi
          GIT_HASH=$(echo $GITHUB_SHA)
          echo ${{ env.GIT_HASH }}
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_PASS }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/IShautsou-ibagroup-eu/argocd-vf-test/actions/variables/LAST_GITHUB_SHA \
            -d "{\"name\":\"LAST_GITHUB_SHA\",\"value\":\"${{ env.GIT_HASH }}\"}"
          git log --pretty=format:'%h %ad | %s%d' --graph --date=short -n 10 || true
