name: Push changes to public

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Version of release'     
        required: true
      DRY_RUN:
        description: 'Preview changes'
        default: true
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
env:
  GITHUB_PASS: ${{ secrets.GIT_PASS }}
  GITHUB_REPO: ${{ vars.PUBLIC_REPO }}
  GITHUB_USER: IShautsou-ibagroup-eu

jobs:
  release_code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo
        uses: actions/checkout@v2
        with:
          path: private_repo
          ref: main
          fetch-depth: 0
      - name: Clone public repo
        uses: actions/checkout@v2
        with:
          path: public_repo2
          token: ${{ secrets.GIT_PASS }}
          repository: ${{ vars.PUBLIC_REPO }}
          ref: main
          fetch-depth: 0
      - name: Commits to public repo
        run: |
          set -e
          cd public_repo2
          git config user.email "ishautsou@ibagroup.eu"
          git config user.name "Ihar Shautsou"
          git remote add private https://github.com/IShautsou-ibagroup-eu/argocd-vf-test.git
          git pull private main
          git tag -f v${{ github.event.inputs.RELEASE_VERSION }}
          if [[ "${{ github.event.inputs.DRY_RUN }}" != "true" ]]; then
            git push -f
            git push --tags
          fi
          git log --pretty=format:'%h %ad | %s%d' --graph --date=short -n 10 || true
#       - name: Commits to public repo
#         run: |
#           set -e
#           cd private_repo
#           git config user.email "ishautsou@ibagroup.eu"
#           git config user.name "Ihar Shautsou"
#           git remote add public https://github.com/IShautsou-ibagroup-eu/test_gitaction_merge.git
#           git fetch
#           git merge
#           git tag -f v${{ github.event.inputs.RELEASE_VERSION }}
#           if [[ "${{ github.event.inputs.DRY_RUN }}" != "true" ]]; then
#             git remote set-url --push origin https://IShautsou-ibagroup-eu:$${{ secrets.GIT_PASS }}@github.com/${GITHUB_REPO}.git
#             git push origin main -f
#             git push origin main --tags
#           fi
#           git log --pretty=format:'%h %ad | %s%d' --graph --date=short -n 10 || true
